### ISSUE TITLE
Hot reload issue

### ISSUE THREAD

**Issue by yathit** [davidmarne/flutter_built_redux#11]
When hot reload the app, store is `null` due to referencing defunct Widget.

**Comment by davidmarne** [comment]
So I played with hot-reload a small amount today with the [todo app](https://github.com/brianegan/flutter_architecture_samples) and ran into an issue with hot-reloads around [this deferred import](https://github.com/brianegan/flutter_architecture_samples/blob/master/lib/src/localizations/messages_all.dart#L11). Once I made that a regular import things worked fine for me when making changes to the build methods of the widgets in that app.

With that said, the issue I saw doesn't sound related to what you are describing. Can post some steps to reproduce?

**Comment by yathit** [comment]
For login/logout logic, I had redux store disposing/re-creating logic. After using the `store` as Widget `ObjectKey` no longer have hot load issue.

Sorry for confusion.
