### ISSUE TITLE
Show this be assert

### ISSUE THREAD

**Issue by yathit** [davidmarne/flutter_built_redux#13]
https://github.com/davidmarne/flutter_built_redux/blob/631cc10d4cda731e8ce9eaf39469a3253a9d0eee/lib/flutter_built_redux.dart#L57

**Comment by davidmarne** [comment]
I agree this would be a good use case for assert, will update.

**Comment by davidmarne** [comment]
https://github.com/davidmarne/flutter_built_redux/pull/14
