### ISSUE TITLE
Update built_value to >= 4 <= 6 ?

### ISSUE THREAD

**Issue by TobiasBales** [davidmarne/flutter_built_redux#15]
When trying to upgrade flutter to the latest alpha release I was not able to find a set of dependencies that worked out for me and one of the constraint's was the pinning of built_value to 4.x

Would it be possible to upgrade the dependency?

The breaking changes apparently are
- Prohibit use of extends in built_value classes. Classes should inherit API using implements and API+implementation using extends Object with.
- Prohibit use of show or as when importing 'package:built_value/built_value.dart'. The generated code needs access to all symbols in the package with no import prefix.
- Prohibit use of the mutable collection types List, Set, Map, ListMultimap and SetMultimap. Suggest built_collection equivalents instead.

Not sure if this causes any issues with flutter_built_redux.

This would be great.

Also: thank you very much for the great project

**Comment by davidmarne** [comment]
merged charafau's update, getting it pushed to pub right now

**Comment by davidmarne** [comment]
Thanks for the heads up! Glad you like it
