### ISSUE TITLE
example app not working

### ISSUE THREAD

**Issue by jt70** [davidmarne/flutter_built_redux#2]
Hi, it seems the example/chat_app is missing the android/ios folders.  If I follow the instructions I get:

> C:\...\flutter_built_redux\example\chat_app>flutter run
Launching lib/main.dart on Android SDK built for x86 in debug mode...
No application found for TargetPlatform.android_x86.
Is your project missing an android/AndroidManifest.xml?
Consider running "flutter create ." to create one.

**Comment by davidmarne** [comment]
whoops! got those files added

**Comment by jt70** [comment]
It's working great now, thanks!!
