### ISSUE TITLE
Don't use the WidgetBuilder name  

### ISSUE THREAD

**Issue by long1eu** [davidmarne/flutter_built_redux#22]
Don't user WidgetBuilder because it conflicts with the WidgetBuilder from the Flutter library.

**Comment by btastic** [comment]
An easy fix would be to write "hide" behind the library and then the class you want to ignore.

So you can just write something like

import 'package:flutter/material.dart' hide WidgetBuilder;

**Comment by long1eu** [comment]
That is not a good idea since we are talking about SDK names. In my opinion this is just bad naming.

**Comment by btastic** [comment]
And I was just giving you an easy advice how to handle it, until the maintainer of this repository is going to decide whether he does it or not.

**Comment by long1eu** [comment]
Thanks!

**Comment by long1eu** [comment]
@btastic I just write you something on gitter

**Comment by davidmarne** [comment]
That's annoying, my bad. I'll get that changed.

**Comment by davidmarne** [comment]
https://github.com/davidmarne/flutter_built_redux/pull/23
