### ISSUE TITLE
Where should I listen to events?

### ISSUE THREAD

**Issue by ga6559** [davidmarne/flutter_built_redux#25]
I want to listen for an specific action and show a `SnackBar` in response to it.

```dart
store
        .actionStream(AppActionsNames.dataCorrupted)
        .listen((change) {
      Scaffold
          .of(context)
          .showSnackBar(SnackBar(content: Text('Data Corrupted')));
    });
```

To do that I need a reference to the `store` and the `context`.

This is my component:
```dart
class AppScreen extends StoreConnector<App, AppActions, App> {
  @override
  Counter connect(App state) => state;

  @override
  Widget build(BuildContext context, Counter state, AppActions actions) {
    return Scaffold(
      appBar: AppBar(
        title: Text('My App'),
      ),
      body: Text('Hello World')
   );
  }
}
```

I'm not sure where should I put the first code because:
1. I don't have access to the `store` and `actionStream` anywhere inside de component.
2. I have access to the `context` only in the build method and it may be called more than once.
3. I must bind the `listen` only 1 time.

Of course I may be designing this thing just the wrong way. I couldn't find any complete example of an flutter application that uses the `listen` binding. Whats the best way to use it in a flutter application?

Thanks.

**Comment by ga6559** [comment]
I've modified the repository to include the init function and it works fine for me. I think this simplify a lot the usage of the library.

The usage would be something like that:
```dart
/// Note that you must add AppBuilder too.
class AppScreen extends StoreConnector<App, AppBuilder, AppActions, App> {
  @override
  App connect(App state) => state;

  @override
  void init(BuildContext context, Store<App, AppBuilder, AppActions> store) {
    // You can use the store to bind listeners and context to interact programmatically with the widget.
    // Examples: take focus out of input, scroll the listview, show a snackbar, etc...
    store.actionStream(AppActionsName.addTodo).listen((change) {});
  }

  @override
  Widget build(BuildContext context, App state, AppActions actions) {
    return Scaffold(
        body: Center(
          child: Text('Hello World'),
        ),
    );
  }
}
```

To make types work I had to add `AppBuilder` to `StoreConnector`,

@davidmarne Can you please take a look and tell me what you think.

Fork: https://github.com/ga6559/flutter_built_redux

**Comment by davidmarne** [comment]
When I wrote the lib I was against subscribing to anything other than state changes, but I hadn't considered this use case. 

I'm guessing dataCorrupted is dispatched by a middleware when an http request or some other async side effect fails? If not I would be curious to get a little more context about your use case.

If that is the case you could consider doing something like this where you send the context as part of the action payload that initiated the http request that caused the error:

Action Payload
```dart
class FormSubmitPayload {
  final ScaffoldState scaffold;
   // other fields
}
```

Widget
```dart
build(context) =>
  MyFormWidget(
    onSubmit: () {
      actions.onFormSubmit(new FormSubmitPayload(
        Scaffold.of(context),
        ..., // other fields,
      ));
    }
  );
```

Middleware Handler
```dart
void MiddlewareApi<Counter, CounterBuilder, CounterActions> api, ActionHandler next, Action<FormSubmitPayload> action
  http.get(url)
    .then(() {
      action.payload.scaffold.showSnackBar(SnackBar(content: Text('Successful Transaction')));
      api.actions.success();
    })
    .catchError(() {
      action.payload.scaffold.showSnackBar(SnackBar(content: Text('Data Corrupted')));
      api.actions.error();
    });
} 
```

Regardless, if something like this doesn't work for you I would like to better understand why.  I'm not against adding the init function but I think that the problem could be solved in another way.

**Comment by ga6559** [comment]
@davidmarne Thanks for the response.

You got it right, the dataCorrupted is called from a middleware that fails to load the data. Unfortunately your solution didn't work for me because I am sharing code between flutter and web, so I can't call `showSnackBar` from a middleware.

I ended up creating a `lastEvent` property in my state that I can listen to inside my views and react to it programmatically. In my views I do something like this `if (state.lastEvent == AppActionNames.dataCorrupted.name)`. I'd prefer to use the built_redux built-in `actionStream`, but for my use case this works just fine.

I still don't see how we could use the `stream` built_redux gives us inside a flutter component. I was thinking that maybe if we could override `initState` and `dispose` inside a StoreConnector, we could bind the listener inside initState and close it in dispose. This is what we do with flutter core components like the `FocusNode`.

Example:
```dart
@override
void initState() {
    super.initState();
    widget.focusNode.addListener(_ensureVisible);
 }

@override
void dispose() {
    super.dispose();
    widget.focusNode.removeListener(_ensureVisible);
}
```

**Comment by ga6559** [comment]
Also, `ReduxProvider` could also give us an `of` method like [this](https://docs.flutter.io/flutter/widgets/InheritedWidget-class.html). That way we could access the store and its stream anywhere in flutter using `ReduxProvider.of(context).store`.
