### ISSUE TITLE
Old dependencies

### ISSUE THREAD

**Issue by BerndWessels** [davidmarne/flutter_built_redux#4]
Hi

I can't use this with the newer versions of `build_redux` and `build_value`.

Are you planning to update this package anytime soon?

Thanks
Bernd

**Comment by davidmarne** [comment]
Shoot my bad, I can get this updated for you tonight.

**Comment by BerndWessels** [comment]
Awesome, looking forward to it, thank you.

Just that you be aware - `built-redux` also seems to have some compatibility issues https://github.com/davidmarne/built_redux/issues/30

**Comment by davidmarne** [comment]
https://github.com/davidmarne/flutter_built_redux/pull/5
