### ISSUE TITLE
Unsubscribe to state when not active route?

### ISSUE THREAD

**Issue by martinory** [davidmarne/flutter_built_redux#40]
Hi!

I changed the formulation of the problem.

When navigating to a new page, the previous page in the router stack still subscribes to the state which results in unnecessary rebuilds which affect performance. 

Is there a way to only subscribe to the state if it is the active one in the router stack?

**Comment by martinory** [comment]
It just hit me that I should break out that part so that it is not part of the tree...

**Comment by abacaj** [comment]
@martinory can't you just use a Route Observer to do the unsubscribing?

https://master-api.flutter.dev/flutter/widgets/RouteObserver-class.html
